# https://docs.travis-ci.com/user/job-lifecycle
sudo: false
services:
  - docker
git:
  depth: false
branches:
  only:
    - gh-pages
    - /.*/
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t bierteam/frontend:$TRAVIS_BRANCH .
  - docker push bierteam/frontend
